return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "stylua",
      "shellcheck",
      "shfmt",
      "flake8",
      "svelte-language-server",
      "typescript-language-server",
      "arduino-language-server",
      "bash-language-server",
      "css-lsp",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "emmet-ls",
      "eslint-lsp",
      "gopls",
      "grammarly-languageserver",
      "graphql-language-service-cli",
      "html-lsp",
      "rust-analyzer",
      "stylelint-lsp",
      "yaml-language-server",
    },
  },
}
